rm(list=ls())
dir.create("~/MyRlibrary",showWarnings=FALSE)
# install the six packages automatically
list.of.packages <- c("proto","gsubfn","DBI","RSQLite","sqldf","labeling","ggplot2", "plyr","coefplot","reshape2","stringr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages(lib.loc = "~/MyRlibrary/")[,"Package"])]
if(length(new.packages)) install.packages(new.packages,lib="~/MyRlibrary/",repos="http://cran.rstudio.com/")
# loading required packages
library(proto,lib.loc = "~/MyRlibrary/")
library(gsubfn,lib.loc = "~/MyRlibrary/")
library(DBI,lib.loc = "~/MyRlibrary/")
library(RSQLite,lib.loc = "~/MyRlibrary/")
library(sqldf,lib.loc = "~/MyRlibrary/")
library(labeling,lib.loc = "~/MyRlibrary/")
library(ggplot2,lib.loc = "~/MyRlibrary/")
library(plyr,lib.loc = "~/MyRlibrary/")
library(coefplot,lib.loc = "~/MyRlibrary/")
library(reshape2,lib.loc = "~/MyRlibrary/")
library(stringr,lib.loc = "~/MyRlibrary/")
# command-line arguments
args <- commandArgs(trailingOnly = TRUE)
# the direcotry of input folder that contains all the txt file generated by "MEGASAT_Genotype.pl"
inputDir <- args[1]
# the directory of output foder that contains all the bar plots for different locus
SaveDir <- args[2]
# extract the output folder name
FolderName <- str_extract(inputDir, "(\\w+\\s*$)")
# create a plot folder in the saving directory
plotDir <- paste(SaveDir,"/Plots_",FolderName,  sep="")
if(!dir.exists(plotDir)){
  dir.create(plotDir)
} else{
  stop(paste("Plots_",FolderName," already exists in the saving directory",sep=""))
}
options (warn=-1)
# copy Genotype.txt to the plot folder
if(file.copy(from=paste (inputDir, "Genotype.txt", sep = "/"), to=paste (plotDir, "Genotype.txt", sep = "/"),overwrite =TRUE,copy.mode = TRUE)==FALSE){
  print("Cannot copy Genotype.txt to plot directory!")
}
# get the files whose names are in a  pattern from the input folder
InfileList = list.files(inputDir,pattern='Genotype_.*\\.txt',recursive=TRUE)
# get the number of files in the input folder
numFile=length(InfileList)
# create a empty list to store the names of all the individual
titleName <- list()
# read one txt file to get all the loci names and put the names into a vector
MyData <- read.csv(paste(inputDir,"/",InfileList[1],sep=""), header=TRUE, sep=",")
lociName <- as.vector(MyData$Microsatellite)
# multiplot function
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  require(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
# generate a fake plot
fakedata <- data.frame(variable="0",value="0")
fakeplot <- ggplot(fakedata,aes(x=variable, y=value))+
  geom_point()+
  ggtitle("fake plot")


for(j in 1:length(lociName)){
  # create an empty list to store all the plots
  plots<-list()
  # generate pdf for each locus
  pdf(file=paste(plotDir,"/",lociName[[j]],".pdf",sep=""),width=15,height=25)
  k=0
  m=0
  num=0
  for(i in InfileList){
    k=k+1
    # get the name of each individual
    s1 = unlist(strsplit(i, split='.', fixed=TRUE))[1]
    titleName[[k]]<- s1
    # read each csv file to get corresponding data for each locus
    db<-read.csv.sql(paste(inputDir,"/",i,sep=""), sql = sprintf("select * from file where Microsatellite = '%s'", lociName[[j]]), header = TRUE, sep = ",",drv = "SQLite")
    if(ncol(db)==3){
      db$X0<-0
      db <- db[,c("Microsatellite","X0","sum","scores")]
    }
    # get the length distribution data, do not need the genotypes
    row <- db[,c(-ncol(db),-(ncol(db)-1))]
    newRow <- melt(row, id.var="Microsatellite")
    # just get the data whose occurence of length is larger than "0"
    boolNewRow <- newRow[,"value"] > 0
    completedb <- newRow[boolNewRow,]
    #remove "x"
    completedb$variable <- as.character(completedb$variable)
    completedb$variable <- str_sub(completedb$variable,2)
    #number of row will be 0 if the value should be larger than 0
    if(nrow(completedb)>0){      
      completedb <- completedb
    } else{
      completedb<-rbind(completedb,data.frame(Microsatellite=lociName[[j]],variable="0",value=0))
    }
    #split the score
    score<-str_split(as.character(db[,ncol(db)]),pattern=" ")
    #get the largest and second largest value then calculate the sum
    v <- completedb$value
    if (length(v) == 1) {
      sum <- max(v,na.rm=TRUE) 
    } else {
      sum <- max(v,na.rm=TRUE) +
        sort(v,partial=length(v)-1)[length(v)-1]
    }
    # variable name "SISLData" is singleIndSingleLocusData
    SISLData <- completedb
    # give different colors to bar plot if their sum is in different range
    if(sum<20){
      SISLData$bar_color = "A"
    } else if(sum<30){
      SISLData$bar_color = "B" 
    } else{
      SISLData$bar_color = "C"
    }
    # give bars that represent real alleles a different color
    SISLData[SISLData$variable == score[[1]][1], c("bar_color") ] = "D"
    SISLData[SISLData$variable == score[[1]][2], c("bar_color") ] = "D"
    SISLData$bar_color <- factor(SISLData$bar_color)
    
    # make the order of the x axis on the right order
    # http://stackoverflow.com/questions/3744178/ggplot2-sorting-a-plot
    SISLData$variable <- factor(SISLData$variable, levels=unique(as.character(SISLData$variable)))
    SISLData$Microsatellite <- as.character(SISLData$Microsatellite)
    colorScheme <- c("A" = "grey", "B" = "pink", "C" =  "deepskyblue", "D" ="dodgerblue4" ) 
    # generate a ggplot for one individual and one locus
    q <- ggplot(data=SISLData, aes(x=variable, y=value, fill=bar_color)) +
      scale_fill_manual(values = colorScheme,breaks= c("A","B","C","D")) +
      geom_bar(stat="identity",show_guide=FALSE)+
      xlab(paste(score[[1]][1], score[[1]][2], sep=","))+
      ggtitle(paste(titleName[[k]],"\n",db[,ncol(db)-1])) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))
    # print 32 plots in one page of a pdf and if the number of individuals
    #is not a multiple of 32, print fake plot into that page
    if(k<=numFile){
      if(m<32){
        m=m+1
        plots[[m]] <- q
      } else{
        layout <- matrix(seq(length(plots)),nrow = 8,  byrow = TRUE)
        multiplot(plotlist=plots,layout=layout)
        num=num+1
        m=1
        plots[[m]] <- q
      }
    }
  }
  while(m<32){
    m=m+1
    plots[[m]] <- fakeplot
  }
  layout <- matrix(seq(length(plots)),nrow = 8,  byrow = TRUE)
  multiplot(plotlist=plots,layout=layout)
  percentage = (j/length(lociName))*100
  writeLines(sprintf("Completed %.2f%% program",percentage))
  dev.off()
}